version: "3.7"

services:
  test:
    build: ./backend
    command: npm test
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "5000:5000"
    command: nodemon -L server.js
    restart: always
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
    links:
      - backend
    ports:
      - "3000:3000"
    restart: always
